services:
  brno-transit:
    build: .
    container_name: brno-transit
    ports:
      - '5000:5000'
    volumes:
      - ./data:/app/data
    environment:
      - IS_DOCKER=True
      - DEBUG_MODE=False
      - RUN_GLOBALLY=True
      - PORT_HTTP_SERVER=5000
    restart: unless-stopped
  